import type { Metadata } from "next";
import Link from "next/link";
import { NavBar } from "@/components/nav-bar";

export const metadata: Metadata = {
  title: "Privacy Policy | RedFlag AI",
  description: "How RedFlag AI handles your data, privacy practices, and your rights.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#0B1120]">
      <NavBar hideHowItWorks />

      <main className="mx-auto max-w-3xl px-4 py-12">
        <h1 className="font-heading text-3xl font-bold text-white">Privacy Policy</h1>
        <p className="mt-2 text-sm text-slate-500">Last updated: March 19, 2026</p>

        <div className="mt-10 space-y-10 text-sm leading-relaxed text-slate-400">
          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-200">1. What We Do</h2>
            <p className="mt-3">
              RedFlag AI analyzes contracts you upload using artificial intelligence. We identify
              potentially risky clauses, provide plain-language explanations, and suggest safer
              alternatives. We are not a law firm and do not provide legal advice.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-200">
              2. Data We Collect
            </h2>
            <div className="mt-3 space-y-3">
              <p>
                <strong className="text-slate-300">Documents you upload:</strong> PDF, DOCX, or TXT
                files. We extract the text content for analysis.
              </p>
              <p>
                <strong className="text-slate-300">Analysis results:</strong> Clause-by-clause risk
                assessments, explanations, and safer alternatives generated by AI.
              </p>
              <p>
                <strong className="text-slate-300">Account information:</strong> If you create an
                account, we store your email address and a hashed password (managed by Supabase
                Auth).
              </p>
              <p>
                <strong className="text-slate-300">Usage metadata:</strong> File type, page count,
                contract type detected, risk scores, analysis timestamps, and pipeline performance
                data (per-step timing, token counts, model used, success or failure). This metadata
                is not encrypted and is used for rate limiting, service operation, and internal
                observability.
              </p>
              <p>
                <strong className="text-slate-300">Rate limiting identifier:</strong> We hash your
                IP address (anonymous users) or user ID (authenticated users) using HMAC-SHA256 to
                enforce daily usage limits. The original IP address is never stored.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-200">
              3. How We Protect Your Data
            </h2>
            <div className="mt-3 space-y-3">
              <p>
                <strong className="text-slate-300">Encryption at rest:</strong> All sensitive data
                (your uploaded document text, filenames, clause analyses, explanations, and safer
                alternatives) is encrypted with AES-256-GCM before being stored in our database.
                Each document has its own derived encryption key. Even our database administrators
                cannot read your contract content.
              </p>
              <p>
                <strong className="text-slate-300">Encrypted file storage:</strong> Uploaded files
                are encrypted before being stored in Supabase Storage.
              </p>
              <p>
                <strong className="text-slate-300">Transport encryption:</strong> All data in
                transit is protected by TLS/HTTPS.
              </p>
              <p>
                <strong className="text-slate-300">IP anonymization:</strong> IP addresses are
                irreversibly hashed using HMAC-SHA256 before storage. We cannot recover the original
                IP address.
              </p>
              <p>
                <strong className="text-slate-300">Row-Level Security:</strong> Database access
                policies ensure authenticated users can only access their own documents.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-200">
              4. Third-Party Data Processing
            </h2>
            <div className="mt-3 space-y-3">
              <p>
                <strong className="text-slate-300">Anthropic (Claude AI):</strong> Your document
                text is sent to Anthropic&apos;s API for analysis. Anthropic does not use API data
                to train their models. Anthropic processes data in accordance with their{" "}
                <a
                  href="https://www.anthropic.com/legal/privacy"
                  className="text-blue-400 hover:text-blue-300 underline"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  privacy policy
                </a>{" "}
                and API terms. Data sent to Anthropic is retained for up to 30 days for trust and
                safety purposes, then deleted.
              </p>
              <p>
                <strong className="text-slate-300">Voyage AI:</strong> Clause text is sent to Voyage
                AI for embedding generation (used to match clauses against our knowledge base of
                known risky patterns). Voyage AI does not store or train on this data.
              </p>
              <p>
                <strong className="text-slate-300">Supabase:</strong> Our database and
                authentication provider. Hosted in EU (eu-west-1). Supabase provides AES-256
                encryption at rest at the infrastructure level, in addition to our application-level
                encryption.
              </p>
              <p>
                <strong className="text-slate-300">Vercel:</strong> Our hosting provider. Serves the
                application and processes requests. Server logs contain only metadata (file types,
                risk scores, timestamps), never contract text or analysis content.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-200">5. Data Retention</h2>
            <div className="mt-3 space-y-3">
              <p>
                <strong className="text-slate-300">Authenticated users:</strong> Documents,
                analyses, and associated data are automatically and permanently deleted 30 days
                after upload by default. You can extend this window from your dashboard, which
                resets the 30-day timer from the date of renewal.
              </p>
              <p>
                <strong className="text-slate-300">Anonymous users:</strong> Data from anonymous
                uploads is deleted when you close the tab (via best-effort browser notification). As
                a safety net, any anonymous data that persists is automatically deleted within 24
                hours.
              </p>
              <p>
                <strong className="text-slate-300">Rate limit data:</strong> Hashed rate-limiting
                identifiers are deleted after 7 days.
              </p>
              <p>
                <strong className="text-slate-300">Account data:</strong> Your email and
                authentication data persist until you delete your account.
              </p>
              <p>
                <strong className="text-slate-300">Immediate deletion:</strong> Authenticated users
                can delete individual analyses from their dashboard or delete their entire account
                and all associated data at any time from their account settings.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-200">
              6. Your Rights (GDPR)
            </h2>
            <div className="mt-3 space-y-3">
              <p>
                If you are located in the European Economic Area, you have the following rights:
              </p>
              <ul className="ml-4 list-disc space-y-2 marker:text-slate-600">
                <li>
                  <strong className="text-slate-300">Right to access:</strong> You can request a
                  copy of your data.
                </li>
                <li>
                  <strong className="text-slate-300">Right to deletion:</strong> You can delete your
                  account and all associated data immediately. All data is also automatically
                  deleted after 30 days.
                </li>
                <li>
                  <strong className="text-slate-300">Right to rectification:</strong> You can
                  re-upload corrected documents at any time.
                </li>
                <li>
                  <strong className="text-slate-300">Right to data portability:</strong> Analysis
                  results can be downloaded as PDF reports.
                </li>
                <li>
                  <strong className="text-slate-300">Right to object:</strong> You can stop using
                  the service at any time. No data is used for profiling or automated
                  decision-making beyond the analysis you explicitly request.
                </li>
              </ul>
              <p>
                To exercise these rights, use the account deletion feature in the application or
                contact us at the address below.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-200">
              7. Cookies and Local Storage
            </h2>
            <div className="mt-3 space-y-3">
              <p>
                <strong className="text-slate-300">Authentication cookies:</strong> Supabase Auth
                uses strictly necessary cookies to maintain your session. These are required for the
                service to function and do not require consent under the ePrivacy Directive.
              </p>
              <p>
                <strong className="text-slate-300">Language preference:</strong> Your selected
                response language is stored in your browser&apos;s localStorage. This is a
                functional preference, not tracking.
              </p>
              <p>We do not use any analytics, advertising, or tracking cookies.</p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-200">8. Children</h2>
            <p className="mt-3">
              RedFlag AI is not intended for use by anyone under the age of 16. We do not knowingly
              collect data from children.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-200">
              9. Changes to This Policy
            </h2>
            <p className="mt-3">
              We may update this policy from time to time. Significant changes will be communicated
              via email to registered users. The &quot;Last updated&quot; date at the top indicates
              the most recent revision.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-200">10. Contact</h2>
            <p className="mt-3">
              For privacy-related questions or to exercise your data rights, contact us at:{" "}
              <a
                href="mailto:privacy@red-flag-ai.com"
                className="text-blue-400 hover:text-blue-300 underline"
              >
                privacy@red-flag-ai.com
              </a>
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-white/5 px-4 py-6">
        <p className="mx-auto max-w-3xl text-center text-xs text-slate-500">
          <Link href="/terms" className="underline hover:text-slate-300">
            Terms of Service
          </Link>
          {" · "}
          <Link href="/" className="underline hover:text-slate-300">
            Back to RedFlag AI
          </Link>
        </p>
      </footer>
    </div>
  );
}
