import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — RedFlag AI",
  description: "How RedFlag AI handles your data, privacy practices, and your rights.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-slate-200 bg-slate-900 px-4 py-6">
        <div className="mx-auto max-w-3xl">
          <Link
            href="/"
            className="font-heading text-lg font-semibold text-white hover:text-slate-300"
          >
            RedFlag AI
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 py-12">
        <h1 className="font-heading text-3xl font-bold text-slate-900">Privacy Policy</h1>
        <p className="mt-2 text-sm text-slate-500">Last updated: March 16, 2026</p>

        <div className="mt-10 space-y-10 text-sm leading-relaxed text-slate-700">
          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">1. What We Do</h2>
            <p className="mt-3">
              RedFlag AI analyzes contracts you upload using artificial intelligence. We identify
              potentially risky clauses, provide plain-language explanations, and suggest safer
              alternatives. We are not a law firm and do not provide legal advice.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">
              2. Data We Collect
            </h2>
            <div className="mt-3 space-y-3">
              <p>
                <strong>Documents you upload:</strong> PDF, DOCX, or TXT files. We extract the text
                content for analysis.
              </p>
              <p>
                <strong>Analysis results:</strong> Clause-by-clause risk assessments, explanations,
                and safer alternatives generated by AI.
              </p>
              <p>
                <strong>Account information:</strong> If you create an account, we store your email
                address and a hashed password (managed by Supabase Auth).
              </p>
              <p>
                <strong>Usage metadata:</strong> File type, page count, contract type detected, risk
                scores, and analysis timestamps. This metadata is not encrypted and is used for rate
                limiting and service operation.
              </p>
              <p>
                <strong>Rate limiting identifier:</strong> We hash your IP address (anonymous users)
                or user ID (authenticated users) using HMAC-SHA256 to enforce daily usage limits.
                The original IP address is never stored.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">
              3. How We Protect Your Data
            </h2>
            <div className="mt-3 space-y-3">
              <p>
                <strong>Encryption at rest:</strong> All sensitive data — your uploaded document
                text, filenames, clause analyses, explanations, and safer alternatives — is
                encrypted with AES-256-GCM before being stored in our database. Each document has
                its own derived encryption key. Even our database administrators cannot read your
                contract content.
              </p>
              <p>
                <strong>Encrypted file storage:</strong> Uploaded files are encrypted before being
                stored in Supabase Storage.
              </p>
              <p>
                <strong>Transport encryption:</strong> All data in transit is protected by
                TLS/HTTPS.
              </p>
              <p>
                <strong>IP anonymization:</strong> IP addresses are irreversibly hashed using
                HMAC-SHA256 before storage. We cannot recover the original IP address.
              </p>
              <p>
                <strong>Row-Level Security:</strong> Database access policies ensure authenticated
                users can only access their own documents.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">
              4. Third-Party Data Processing
            </h2>
            <div className="mt-3 space-y-3">
              <p>
                <strong>Anthropic (Claude AI):</strong> Your document text is sent to
                Anthropic&apos;s API for analysis. Anthropic does not use API data to train their
                models. Anthropic processes data in accordance with their{" "}
                <a
                  href="https://www.anthropic.com/legal/privacy"
                  className="text-blue-600 hover:text-blue-700 underline"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  privacy policy
                </a>{" "}
                and API terms. Data sent to Anthropic is retained for up to 30 days for trust and
                safety purposes, then deleted.
              </p>
              <p>
                <strong>Voyage AI:</strong> Clause text is sent to Voyage AI for embedding
                generation (used to match clauses against our knowledge base of known risky
                patterns). Voyage AI does not store or train on this data.
              </p>
              <p>
                <strong>Supabase:</strong> Our database and authentication provider. Hosted in EU
                (eu-west-1). Supabase provides AES-256 encryption at rest at the infrastructure
                level, in addition to our application-level encryption.
              </p>
              <p>
                <strong>Vercel:</strong> Our hosting provider. Serves the application and processes
                requests. Server logs contain only metadata (file types, risk scores, timestamps) —
                never contract text or analysis content.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">5. Data Retention</h2>
            <div className="mt-3 space-y-3">
              <p>
                <strong>Automatic deletion:</strong> All documents, analyses, and associated data
                are automatically and permanently deleted 30 days after upload. This applies to all
                users, whether authenticated or anonymous.
              </p>
              <p>
                <strong>Rate limit data:</strong> Hashed rate-limiting identifiers are deleted after
                7 days.
              </p>
              <p>
                <strong>Account data:</strong> Your email and authentication data persist until you
                delete your account.
              </p>
              <p>
                <strong>Immediate deletion:</strong> Authenticated users can delete their account
                and all associated data at any time from their account settings.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">
              6. Your Rights (GDPR)
            </h2>
            <div className="mt-3 space-y-3">
              <p>
                If you are located in the European Economic Area, you have the following rights:
              </p>
              <ul className="ml-4 list-disc space-y-2">
                <li>
                  <strong>Right to access:</strong> You can request a copy of your data.
                </li>
                <li>
                  <strong>Right to deletion:</strong> You can delete your account and all associated
                  data immediately. All data is also automatically deleted after 30 days.
                </li>
                <li>
                  <strong>Right to rectification:</strong> You can re-upload corrected documents at
                  any time.
                </li>
                <li>
                  <strong>Right to data portability:</strong> Analysis results can be downloaded as
                  PDF reports.
                </li>
                <li>
                  <strong>Right to object:</strong> You can stop using the service at any time. No
                  data is used for profiling or automated decision-making beyond the analysis you
                  explicitly request.
                </li>
              </ul>
              <p>
                To exercise these rights, use the account deletion feature in the application or
                contact us at the address below.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">
              7. Cookies and Local Storage
            </h2>
            <div className="mt-3 space-y-3">
              <p>
                <strong>Authentication cookies:</strong> Supabase Auth uses strictly necessary
                cookies to maintain your session. These are required for the service to function and
                do not require consent under the ePrivacy Directive.
              </p>
              <p>
                <strong>Language preference:</strong> Your selected response language is stored in
                your browser&apos;s localStorage. This is a functional preference, not tracking.
              </p>
              <p>We do not use any analytics, advertising, or tracking cookies.</p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">8. Children</h2>
            <p className="mt-3">
              RedFlag AI is not intended for use by anyone under the age of 16. We do not knowingly
              collect data from children.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">
              9. Changes to This Policy
            </h2>
            <p className="mt-3">
              We may update this policy from time to time. Significant changes will be communicated
              via email to registered users. The &quot;Last updated&quot; date at the top indicates
              the most recent revision.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">10. Contact</h2>
            <p className="mt-3">
              For privacy-related questions or to exercise your data rights, contact us at:{" "}
              <a
                href="mailto:privacy@red-flag-ai.com"
                className="text-blue-600 hover:text-blue-700 underline"
              >
                privacy@red-flag-ai.com
              </a>
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-slate-200 bg-slate-100 px-4 py-6">
        <p className="mx-auto max-w-3xl text-center text-xs text-slate-500">
          <Link href="/terms" className="underline hover:text-slate-700">
            Terms of Service
          </Link>
          {" · "}
          <Link href="/" className="underline hover:text-slate-700">
            Back to RedFlag AI
          </Link>
        </p>
      </footer>
    </div>
  );
}
