import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | RedFlag AI",
  description: "Terms and conditions for using RedFlag AI contract analysis.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-slate-200 bg-slate-900 px-4 py-6">
        <div className="mx-auto max-w-3xl">
          <Link
            href="/"
            className="font-heading text-lg font-semibold text-white hover:text-slate-300"
          >
            RedFlag AI
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 py-12">
        <h1 className="font-heading text-3xl font-bold text-slate-900">Terms of Service</h1>
        <p className="mt-2 text-sm text-slate-500">Last updated: March 16, 2026</p>

        <div className="mt-10 space-y-10 text-sm leading-relaxed text-slate-700">
          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">
              1. Acceptance of Terms
            </h2>
            <p className="mt-3">
              By accessing or using RedFlag AI (&quot;the Service&quot;), you agree to be bound by
              these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">
              2. Service Description
            </h2>
            <p className="mt-3">
              RedFlag AI is an AI-powered contract analysis tool. You upload a contract document,
              and the Service provides clause-by-clause risk analysis, explanations, and suggested
              safer alternatives. The Service supports PDF, DOCX, and TXT file formats.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">
              3. Not Legal Advice
            </h2>
            <div className="mt-3 space-y-3 rounded-md border border-amber-200 bg-amber-50 p-4">
              <p className="font-semibold text-amber-900">
                RedFlag AI does not provide legal advice.
              </p>
              <p className="text-amber-800">
                Analysis results are generated by artificial intelligence and may contain errors,
                omissions, or inaccuracies. The Service is not a substitute for professional legal
                counsel. You should always consult a qualified attorney before making legal
                decisions or signing contracts based on the analysis provided.
              </p>
              <p className="text-amber-800">
                We make no warranties or representations regarding the accuracy, completeness, or
                reliability of the analysis. Any reliance you place on the results is strictly at
                your own risk.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">4. Acceptable Use</h2>
            <div className="mt-3 space-y-3">
              <p>You agree to:</p>
              <ul className="ml-4 list-disc space-y-2">
                <li>Only upload documents that you have the legal right to share</li>
                <li>Not upload documents containing malware or malicious content</li>
                <li>Not attempt to circumvent rate limits or security measures</li>
                <li>Not use the Service for any illegal purpose</li>
                <li>
                  Not reverse-engineer, scrape, or systematically extract data from the Service
                </li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">5. Usage Limits</h2>
            <div className="mt-3 space-y-3">
              <p>
                <strong>Anonymous users:</strong> 1 analysis per day.
              </p>
              <p>
                <strong>Authenticated users:</strong> 3 analyses per day.
              </p>
              <p>
                <strong>File limits:</strong> PDFs up to 30 pages; DOCX and TXT files up to 90,000
                characters. Maximum file size: 10 MB.
              </p>
              <p>
                These limits may change at our discretion. Abuse of the Service may result in
                temporary or permanent access restrictions.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">6. User Accounts</h2>
            <div className="mt-3 space-y-3">
              <p>
                You may use the Service without an account, subject to lower usage limits. Creating
                an account provides higher limits and the ability to access past analyses.
              </p>
              <p>
                You are responsible for maintaining the security of your account credentials. You
                must notify us immediately if you suspect unauthorized access to your account.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">7. Data Handling</h2>
            <div className="mt-3 space-y-3">
              <p>
                Your use of the Service is also governed by our{" "}
                <Link href="/privacy" className="text-blue-600 hover:text-blue-700 underline">
                  Privacy Policy
                </Link>
                .
              </p>
              <p>Key points:</p>
              <ul className="ml-4 list-disc space-y-2">
                <li>Document content is encrypted at rest using AES-256-GCM</li>
                <li>All data is automatically deleted after 30 days</li>
                <li>
                  Document text is sent to Anthropic (Claude AI) and Voyage AI for analysis. These
                  providers do not use API data for model training
                </li>
                <li>You can delete your account and data at any time</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">
              8. Intellectual Property
            </h2>
            <div className="mt-3 space-y-3">
              <p>
                <strong>Your documents:</strong> You retain all rights to documents you upload. We
                do not claim any ownership of your content.
              </p>
              <p>
                <strong>Analysis output:</strong> AI-generated analysis results are provided for
                your personal use. The underlying AI models, knowledge base, prompts, and
                application code remain our property.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">
              9. Limitation of Liability
            </h2>
            <div className="mt-3 space-y-3">
              <p>
                To the maximum extent permitted by law, RedFlag AI and its operators shall not be
                liable for any indirect, incidental, special, consequential, or punitive damages
                resulting from your use of the Service.
              </p>
              <p>
                This includes, without limitation, damages arising from: reliance on analysis
                results, decisions made based on AI-generated recommendations, loss of data, or
                service interruptions.
              </p>
              <p>
                Our total liability for any claim arising from the Service shall not exceed the
                amount you paid for the Service in the 12 months preceding the claim (which may be
                zero for free-tier users).
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">10. Availability</h2>
            <p className="mt-3">
              We strive to keep the Service available but do not guarantee uninterrupted access. We
              may modify, suspend, or discontinue the Service at any time without notice. We are not
              liable for any downtime or service interruption.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">
              11. Changes to These Terms
            </h2>
            <p className="mt-3">
              We may update these Terms from time to time. Continued use of the Service after
              changes constitutes acceptance. Significant changes will be communicated to registered
              users via email.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">12. Governing Law</h2>
            <p className="mt-3">
              These Terms are governed by the laws of the European Union and the applicable member
              state where the Service operator is established. Disputes shall be resolved in the
              competent courts of that jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-slate-900">13. Contact</h2>
            <p className="mt-3">
              Questions about these Terms? Contact us at:{" "}
              <a
                href="mailto:legal@red-flag-ai.com"
                className="text-blue-600 hover:text-blue-700 underline"
              >
                legal@red-flag-ai.com
              </a>
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-slate-200 bg-slate-100 px-4 py-6">
        <p className="mx-auto max-w-3xl text-center text-xs text-slate-500">
          <Link href="/privacy" className="underline hover:text-slate-700">
            Privacy Policy
          </Link>
          {" · "}
          <Link href="/" className="underline hover:text-slate-700">
            Back to RedFlag AI
          </Link>
        </p>
      </footer>
    </div>
  );
}
